
name: Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Update dependent
        run: |
          sudo apt-get update -y
          make

      - name: Push to branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: archive
          folder: out
